config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get('/', to: "welcome#root", as: :root)

  resources :tasks
  get('/complete_task/:id/', to: "tasks#complete_task", as: :complete_task)

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    if user.is_admin?
      can :manage, :all 
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    alias_action :create, :read, :update, :destroy, :complete_task, to: :crud

    can(:crud, Task) do |task|
      task.user == user 
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    validates :title, presence: true , length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    # Authentication
    # -  We need to have users in our app to authenticate
    # -  and that including Sign Up (registration or create
    #    a user in user's table) and Sign In(creating a session)

    # We use bcypt to secure the password and save them as a
    # hash in our user's table. And for that we need
    #   1 - User's table
    #   2 - bcrypt gem 
    #   3 - a field in user's table that's called password_digest
    #   4 - having has_secure_password in user's model

    has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private 

    def current_user
        if session[:user_id].present?
            @current_user ||= User.find session[:user_id] # ||= will only assign
            # @current_user if it is nil. otherwise continue using it as it is
        end
    end
    helper_method :current_user 
    # helper_method is a rails method that makes controller methods available
    # as helpers on views

    def user_signed_in? 
        current_user.present? 
    end
    helper_method :user_signed_in?

    def authenticate_user! 
        unless user_signed_in? 
            flash[:danger] = "You need to be signed in first!"
            redirect_to new_session_path
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new 
    end

    def create 
        user = User.find_by_email params[:email]
        # has_secure_password gives us the instance method authenticate used to
        # check passwords
        # user& is a little bit of meta-programming. This is basically checks if
        # user is NOT nil before trying to call .authenticate. This is to avoid 
        # no method errors.
        if user&.authenticate params[:password]
            session[:user_id] = user.id
            session[:fav_animal] = 'Wolf'
            # session is a hash that is available anywhere. Rails will grab all the
            # information from session and create a cookie with the data.
            # A cokie is just a string of key value pairs
            # { session: { user_id: 1, fav_animal: 'Wolf' }}
            flash[:success] = "User Logged In"
            redirect_to tasks_path
        else 
            # flash = {}
            flash[:warning] = "Couldn't Sign In"
            # flash = { warning: "Couldn't Sign In"}
            flash[:secondary] = "what happend!!"
            # flash = { warning: "Couldn't Sign In", secondary: "what happend!!"}
            render :new
        end
    end

    def destroy 
        session[:user_id] = nil 
        redirect_to tasks_path
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :find_task, only: [:show, :edit, :update, :destroy, :complete_task]
    before_action :authenticate_user!
    before_action :authorize!, only: [:edit, :update, :destroy, :complete_task]
    # show the list of tasks
    def index 
        @tasks = Task.where(user_id: current_user.id).order(created_at: :desc)
    end

    def new
        @task = Task.new # we need an instance of our resource to be used with 'form_with'
    end

    def create
        @task = Task.new(params.require(:task).permit(:title))
        @task.user = current_user
        if @task.save 
            redirect_to task_path(@task)
        else
            redirect_to new_task_path
        end
    end

    def show 
    end

    def destroy
        @task.destroy 
        redirect_to tasks_path
    end

    def edit 
    end

    def update 
        if @task.update(params.require(:task).permit(:title))
            @task.update_attribute(:is_complete, false)
            redirect_to task_path(@task)
        else
            render :edit 
        end
    end

    def complete_task 
        is_complete_val = @task.is_complete ? false : true
        if @task.update_attribute(:is_complete, is_complete_val)
            redirect_to task_path(@task)
        else
            render :show 
        end
       
    end
    
    private

    def find_task 
        @task = Task.find params[:id]
    end

    def authorize!
        redirect_to root_path, alert: 'Not Authorized' unless can?(:crud, @task)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new 
        @user = User.new 
        # form_with uses an instance to create a form 
    end 

    def create 
        @user = User.new params.require(:user).permit(:first_name, :last_name, :email, :password, :pass_confirmation)
        if @user.save 
            flash.delete(:warning)
            session[:user_id] = @user.id
            redirect_to tasks_path 
        else 
            flash[:warning] = "Unable to create user"
            render :new 
        end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def root 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListWithAuth</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
    <% flash.each do |type, message| %>
      <div class='bg-<%= type %> p-3 rounded mb-2 shadow-sm'>
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav>
    <ul>
        <% if user_signed_in? %>
            <%= link_to 'Tasks List', tasks_path %>
            |
            <%= link_to 'New Task', new_task_path %>
            |
            <%= current_user.first_name %>
            |
            <%= link_to 'Sign Out', session_path, method: :delete %>
        <% else %>
            <%= link_to 'Sign In', new_session_path %>
            |
            <%= link_to 'Sign Up', new_user_path %>
        <% end %>
    </ul>
</nav>

app/views/tasks/_form.html.erb
<% if @task.errors.present? %>
    <p>
        <%= @task.errors.full_messages.join(', ') %>
    </p>
<% end %>

<%= form_with model: @task, local: true do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.submit %>
    </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>The List of Tasks</h1>
<div>
    <% @tasks.each do |task| %>
        <%= link_to task do %>
            <li>
                <%= task.title %>
            </li>
        <% end %>
    <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task, local: true do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
        <%= f.submit 'Add Task' %>
    </div>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= time_ago_in_words(@task.created_at) %></p>
<strong><%= @task.user.first_name %> <%= @task.user.last_name %></strong>
<hr />
<% if can? :crud, @task %>
    <% if @task.is_complete %>
        <%= link_to(
            'Set to Undone',
            complete_task_path(@task.id)
        )%>
    <% else %>
        <%= link_to(
            'Set to Done',
            complete_task_path(@task.id)
        )%>
    <% end %>
    <div>
        <%= link_to(
            'Edit',
            edit_task_path(@task),
        )%>
        |
        <%= link_to(
            'Delete', 
            task_path(@task),
            method: :delete,
            data: { confirm: 'are you sure?' }
        )%>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>User New Page</h1>
<% if @user.errors.present? %>
    <p>
        <%= @user.errors.full_messages.join(', ') %>
    </p>
<% end %>

<div class="shadow-sm p-3 mb-5 bg-white rounded">
    <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>

        <%= f.submit 'Create User', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/welcome/root.html.erb
<h1>Welcome to Your Tasks Dashboard</h1>